site_name: Méthodes agiles et techniques de développement
nav:
    - Accueil: index.md
    - Déroulement des séances: planning.md
    - Roadmaps:
        - Utilisateurices: utilisateurs.md
        - Product Owner (PO): po.md
        - Chef·fe d'équipe MOE: chef_moe.md
        - Développeur·euses: developpeurs.md
        - DevOps: devops.md
    - Aide Gitlab:
        - Créer un projet: gitlab/project.md
        - Tickets: gitlab/issues.md
        - Merge requests: gitlab/mr.md
        - Création de version: gitlab/tag.md
        - Intégration continue: gitlab/ci.md
    - Git:
        - Guide pour débuter (en anglais): https://rogerdudler.github.io/git-guide/" target="_blank
        - Formation Git: FormationGit.pdf" target="_blank
    - Support de la première demi-journée: presentation_j1.md
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - fenced_code
    - toc:
        baselevel: 2
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details

theme:
  name: material
  language: fr
  palette:
    primary: blue grey
    accent: deep purple
  logo: logo.svg
  favicon: logo.svg
  features:
    - content.code.copy
plugins:
  - search
  - slides
